apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
spec:
  replicas: 10
  selector:  
    matchLabels:
      app: nginx-color
  template:
    metadata:
    
      labels:
        app: nginx-color
    spec:
      containers:
        - name: nginx-color
          image: kubedevio/nginx-color:blue

